core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('alumni/', views.alumni, name='alumni'),
    path('about/', views.about, name='about'),
]

dashboard/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
]

tracerstudy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('dashboard/', include('dashboard.urls')),
]

alumni/models.py
from django.db import models
from school.models import School, Vocation

# Create your models here.
class Alumni(models.Model):
    school = models.OneToOneField(School, related_name='alumni', on_delete=models.CASCADE)
    vocation = models.OneToOneField(Vocation, related_name='alumni', on_delete=models.CASCADE)
    nisn = models.IntegerField(blank=True, null=True)
    nik = models.IntegerField(blank=True, null=True)
    nama_alumni = models.CharField(max_length=255, null=True)
    
    male = 'laki-laki'
    female = 'perempuan'
    CHOICES_GENDER = (
        (male, 'laki-laki'),
        (female, 'perempuan'),
    )
    gender = models.CharField(max_length=20, choices=CHOICES_GENDER, null=True)
    tgl_lahir = models.CharField(max_length=50, blank=True, null=True)
    thn_lulus = models.IntegerField(blank=True, null=True)

    class Meta:
        ordering = ('nama_alumni', 'thn_lulus',)
    
    def __str__(self):
        return self.nisn

core/models.py
from django.db import models

# Create your models here.

dashboard/models.py
from django.db import models

# Create your models here.

school/models.py
from django.db import models

# Create your models here.
class School(models.Model):
    npsn = models.IntegerField(unique=True)
    name = models.CharField(max_length=100, null=True)
    address = models.TextField()
    provinsi = models.CharField(max_length=100, null=True)
    kabupaten = models.CharField(max_length=100, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class Vocation(models.Model):
    bidang = models.CharField(max_length=255, null=True)
    program = models.CharField(max_length=255, null=True)
    kompetensi = models.CharField(max_length=255, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.kompetensi

userprofile/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Userprofile(models.Model):
    admin = 'admin'
    staff = 'staff'

    CHOICES_ROLE = (
        (admin, 'admin'),
        (staff, 'staff'),
    )

    user = models.OneToOneField(User, related_name='userprofile', on_delete=models.CASCADE)
    role = models.CharField(max_length=10, choices=CHOICES_ROLE, default=admin, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('user',)

    def __str__(self):
        return self.role

core/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Masukan Username',
        'class': 'form-control',
        'autocomplete': 'off',
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Masukan Username',
        'class': 'form-control',
        'autocomplete': 'off',
    }))

alumni/views.py
from django.shortcuts import render

# Create your views here.

core/views.py
from django.shortcuts import render, redirect
from .forms import LoginForm
from django.contrib import messages
from django.contrib.auth import authenticate, logout, login

# Create your views here.
def home(request):
    return render(request, 'core/home.html')

def alumni(request):
    return render(request, 'core/alumni.html')

def about(request):
    return render(request, 'core/about.html')

def login_view(request):
    form = LoginForm(request.POST)
    if request.user.is_authenticated:
        return redirect('dashboard')
    
    if request.method == 'GET':
        return render(request, 'core/login.html', {
            'form': form
        })
    
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            messages.success(request, 'You are logged in.')
            return redirect('dashboard')
        else:
            messages.warning(request, 'User does not exiest.')
            return render(request, 'core/login.html', {
                'form': form
            })
        
def logout_view(request):
    logout(request)
    messages.success(request, 'You logged out')
    return redirect('core:login')

dashboard/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def dashboard(request):
    if request.user.is_superuser == True:
        return redirect('admin:index')
    else:
        return render(request, 'dashboard/dashboard.html')

templates/core/about.html
{% extends "core/index.html" %}

{% block title %}About{% endblock  %}
{% load static %}

{% block layouts %}
<h1>Ini About</h1>
{% endblock  %}

templates/core/alumni.html
{% extends "core/index.html" %}

{% block title %}Alumni{% endblock  %}
{% load static %}

{% block layouts %}

{% endblock  %}

templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="description" content="" />

    <link rel="icon" type="image/x-icon" href="{% static "assets/img/logo.webp" %}" />
    <link rel="stylesheet" href="{% static "assets/vendor/fonts/boxicons.css" %}" />
    <link rel="stylesheet" href="{% static "assets/vendor/css/core.css" %}" class="template-customizer-core-css" />
    <link rel="stylesheet" href="{% static "assets/vendor/css/theme-default.css" %}" class="template-customizer-theme-css" />
    <link rel="stylesheet" href="{% static "assets/css/demo.css" %}" />
    <link rel="stylesheet" href="{% static "assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css" %}" />
    <link rel="stylesheet" href="{% static "assets/vendor/libs/apex-charts/apex-charts.css" %}" />

    <link rel="stylesheet" href="{% static "assets/vendor/css/pages/page-auth.css" %}" />

    <script src="{% static "assets/vendor/js/helpers.js" %}"></script>
    <script src="{% static "assets/js/config.js" %}"></script>

    <title>TracerStudy | {% block title %}{% endblock %}</title>
</head>
<body>
    {% block content %}
    {% endblock %}

    <script src="{% static "assets/vendor/libs/jquery/jquery.js" %}"></script>
    <script src="{% static "assets/vendor/libs/popper/popper.js" %}"></script>
    <script src="{% static "assets/vendor/js/bootstrap.js" %}"></script>
    <script src="{% static "assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js" %}"></script>
    <script src="{% static "assets/vendor/js/menu.js" %}"></script>
    <script src="{% static "assets/vendor/libs/apex-charts/apexcharts.js" %}"></script>
    <script src="{% static "assets/js/main.js" %}"></script>
    <script src="{% static "assets/js/dashboards-analytics.js" %}"></script>
</body>
</html>

templates/core/footer.html
<footer class="content-footer footer bg-footer-theme">
    <div class="container-xxl d-flex flex-wrap justify-content-between py-2 flex-md-row flex-column">
        <div class="mb-2 mb-md-0">
            Copyright ©
            <script>
            document.write(new Date().getFullYear());
            </script>
            <a href="" class="footer-link fw-bolder">TracerStudy</a>
            . SMK PGRI 4 TANGGUL
        </div>
    </div>
</footer>

templates/core/home.html
{% extends "core/index.html" %}

{% block title %}Home{% endblock  %}
{% load static %}

{% block layouts %}
<h1>Ini Home</h1>
{% endblock  %}

templates/core/index.html
{% extends "core/base.html" %}%}

{% block title%}Index{% endblock%}
{% load static %}

{% block content %}
<div class="layout-wrapper layout-content-navbar">
    <div class="layout-container">
        <!-- Menu -->
        <aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
            <div class="app-brand demo">
                <a href="{% url 'core:home' %}" class="app-brand-link">
                    <span class="app-brand-logo demo">
                        <img src="{% static "assets/img/logo.webp" %}" width="40" height="36">
                    </span>
                    <span class="app-brand-text demo menu-text fw-bolder ms-2">TracerStudy</span>
                </a>

                <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
                    <i class="bx bx-chevron-left bx-sm align-middle"></i>
                </a>
            </div>

            <div class="menu-inner-shadow"></div>

            <ul class="menu-inner py-1">
                <li class="menu-item {% if request.resolver_match.url_name == "home" %}active{% endif %}">
                    <a href="{% url 'core:home' %}" class="menu-link">
                        <i class="menu-icon tf-icons bx bx-home-circle"></i>
                        <div data-i18n="Analytics">Home</div>
                    </a>
                </li>
                <li class="menu-item {% if request.resolver_match.url_name == "alumni" %}active{% endif %}">
                    <a href="{% url 'core:alumni' %}" class="menu-link">
                        <i class="menu-icon tf-icons bx bxs-graduation"></i>
                        <div data-i18n="Analytics">Alumni</div>
                    </a>
                </li>
                <li class="menu-item {% if request.resolver_match.url_name == "about" %}active{% endif %}">
                    <a href="{% url 'core:about' %}" class="menu-link">
                        <i class="menu-icon tf-icons bx bxs-contact"></i>
                        <div data-i18n="Analytics">About</div>
                    </a>
                </li>
                <li class="menu-item">
                    <a href="{% url 'core:login' %}" class="menu-link">
                        <i class="menu-icon tf-icons bx bx-lock-open-alt"></i>
                        <div data-i18n="Analytics">Login</div>
                    </a>
                </li>
            </ul>
        </aside>
        <!-- / Menu -->

        <!-- Layout container -->
        <div class="layout-page">
            <!-- Navbar -->
            <nav class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme" id="layout-navbar">
                <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
                    <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
                        <i class="bx bx-menu bx-sm"></i>
                    </a>
                </div>
            </nav>
            <!-- / Navbar -->

            <!-- Content wrapper -->
            <div class="content-wrapper">
                <!-- Content -->
                <div class="container-xxl flex-grow-1 container-p-y">
                    <div class="row">
                        {% block layouts %}{% endblock  %}
                    </div>
                </div>
                <!-- / Content -->

                <!-- Footer -->
                {% include 'core/footer.html' %}
                <!-- / Footer -->

                <div class="content-backdrop fade"></div>
            </div>
            <!-- Content wrapper -->
        </div>
        <!-- / Layout page -->
    </div>

    <!-- Overlay -->
    <div class="layout-overlay layout-menu-toggle"></div>
</div>
{% endblock %}

templates/core/login.html
{% extends "core/base.html" %}%}

{% block title%}Login{% endblock%}
{% load static %}

{% block content %}
<div class="container-xxl">
    <div class="authentication-wrapper authentication-basic container-p-y">
        <div class="authentication-inner">
            <!-- Login -->
            <div class="card">
                <div class="card-body">
                    <!-- Logo -->
                    <div class="app-brand justify-content-center">
                        <a class="app-brand-link gap-2">
                            <img src="{% static "assets/img/logo.webp" %}" width="60" height="56">
                            <span class="app-brand-text demo text-body fw-bolder">Tracer Study</span>
                        </a>
                    </div>
                    <!-- /Logo -->
                    <center><h4 class="mb-2">SMKS PGRI 4 TANGGUL</h4></center>
                    <p class="mb-4">Silakan Login !. Jika belum ada akun, mohon menghubungi staff (082140361163).</p>

                    <form id="formAuthentication" class="mb-3" action="." method="POST">
                        {% csrf_token %}

                        {{ form.non_field_errors }}

                        <div class="mb-3">
                            <label for="username" class="form-label">Username</label>
                            {{ form.username }}
                        </div>
                        <div class="mb-3">
                            <label class="form-label" for="password">Password</label>
                            {{ form.password }}
                        </div>

                        {% if form.errors or form.non_field_errors %}
                            <div class="alert alert-danger" role="alert">
                                {% for field in form %}
                                    {{ field.errors }}
                                {% endfor %}
                            </div>
                        {% endif %}
                    
                        <div class="mb-3">
                            <button class="btn btn-primary mx-3" type="submit">Sign in</button>
                        </div>
                    </form>
                </div>
            </div>
            <!-- /Login -->
        </div>
    </div>
</div>
{% endblock %}